### ISSUE TITLE
Throws exception on non-gerber files

### ISSUE THREAD

**Issue by henrikekblad** [mcous/gerber-to-svg#22] opened 2015-09-25 05:40 UTC
When running my test-files I got an exception when feeding the following files:
https://github.com/mgebundy/LilyPad-SR/tree/master/gerber

[Error: Error at line 17 - Cannot read property 'flashed' of undefined]
at module.exports (/Users/hek/git/nodebb-plugin-gerber3d/node_modules/gerber-to-svg/lib/gerber-to-svg.js:90:13)

**Comment by mcous** [comment] 2016-05-02 04:23
Just kidding this is still a problem

**Comment by mcous** [comment] 2016-06-11 16:29
As of 2.0.0 this particular file is not longer causing problems, so I'm going to close this issue again. This particular error was caused by an overly lenient regex in the drill file parser of gerber-parser. Will reopen or file new issues if this continues to be a problem.

**Closed by mcous** 2016-06-11 16:29 UTC
Labels: bug, gerber-parser

**Comment by henrikekblad** [comment] 2016-06-11 21:52
👍
